[package]
name = "ls_oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
humansize = "2.1.3"
tempfile = "3.15.0"
users = "0.11.0"
